name = "MortalityTables"
uuid = "4780e19d-04b9-53dc-86c2-9e9aa59b5a12"
authors = ["Alec Loudenback <alecloudenback@gmail.com>"]
version = "0.6.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
XMLDict = "228000da-037f-5747-90a9-8195ccbf91a5"

[compat]
DataStructures = "^0.16, 0.17"
ProgressMeter = "^1.2"
XMLDict = "0.4"
julia = "^1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
